<template>
  <div class="ranking" aria-label="하나의 prompt에서 여러 response를 생성하고 사람이 선호 순서를 매기는 과정">
    <div class="prompt"><span>PROMPT</span><strong>하나의 질문</strong></div>
    <div class="fanout" aria-hidden="true"><i></i><i></i><i></i><i></i></div>
    <div class="responses"><div>A</div><div class="preferred">B</div><div>C</div><div>D</div></div>
    <div class="judge"><span>HUMAN PREFERENCE</span><div class="person"><i></i><b>비교</b></div><strong>B &gt; A &gt; D &gt; C</strong><small>정답을 직접 쓰기보다 순서를 선택</small></div>
  </div>
</template>

<style scoped>
.ranking { height:274px; display:grid; grid-template-columns:1.15fr .85fr; grid-template-rows:52px 28px 1fr; gap:0 22px; }.prompt { grid-column:1; justify-self:center; width:200px; padding:10px 16px; display:flex; align-items:baseline; justify-content:center; gap:10px; border:1px solid rgba(173,124,255,.4); border-radius:var(--radius-md); background:var(--color-bg-raised); }.prompt span { color:var(--color-muted); font:700 9px/1 ui-monospace; letter-spacing:.08em; }.prompt strong { color:var(--color-text); font-size:14px; }.fanout { grid-column:1; width:78%; justify-self:center; display:grid; grid-template-columns:repeat(4,1fr); border-top:1px solid rgba(173,124,255,.4); transform:translateY(14px); }.fanout i { justify-self:center; width:1px; height:25px; background:rgba(173,124,255,.4); }.responses { grid-column:1; display:grid; grid-template-columns:repeat(4,1fr); gap:10px; align-items:start; }.responses div { height:136px; display:grid; place-items:center; border:1px solid var(--color-line); border-radius:var(--radius-lg); background:var(--color-surface); color:var(--color-text-soft); font-size:23px; font-weight:760; }.responses .preferred { border-color:var(--color-rl); border-top:3px solid var(--color-rl); color:var(--color-rl); background:rgba(173,124,255,.06); }.judge { grid-column:2; grid-row:1 / 4; padding:22px; display:flex; flex-direction:column; align-items:center; justify-content:center; text-align:center; border:1px solid rgba(173,124,255,.42); border-radius:var(--radius-lg); background:rgba(173,124,255,.035); }.judge > span { color:var(--color-muted); font:700 10px/1 ui-monospace; letter-spacing:.1em; }.person { margin:20px 0 14px; display:flex; align-items:center; gap:10px; }.person i { position:relative; width:40px; height:40px; border:1px solid var(--color-rl); border-radius:50%; }.person i::after { content:""; position:absolute; left:8px; right:8px; bottom:-12px; height:17px; border:1px solid var(--color-rl); border-radius:18px 18px 0 0; }.person b { color:var(--color-rl); font-size:14px; }.judge strong { color:var(--color-text); font-size:23px; margin-top:8px; }.judge small { color:var(--color-muted); font-size:11px; margin-top:12px; }
</style>
