<template>
  <div class="reward-compare" aria-label="Open-ended human preference와 자동 검증 가능한 reward의 비교">
    <section class="reward reward--human"><header><span>OPEN-ENDED</span><strong>Human Preference</strong></header><div class="human"><i></i><b>“어떤 답이 더 좋은가?”</b></div><footer>도움됨 · 표현 · 안전</footer></section>
    <div class="versus">VS</div>
    <section class="reward reward--verify"><header><span>CHECKABLE OUTCOME</span><strong>Verifiable Reward</strong></header><div class="checks"><div><b>Math</b><span>정답 checker</span><i>✓</i></div><div><b>Code</b><span>unit test</span><i>✓</i></div><div><b>Format</b><span>rule checker</span><i>✓</i></div></div><footer>자동으로 correctness 확인</footer></section>
    <div class="scale-note"><span>사람의 판단이 필요한 문제</span><i></i><strong>자동 검증 가능한 문제에서 reward를 확장</strong></div>
  </div>
</template>

<style scoped>
.reward-compare { height:274px; display:grid; grid-template-columns:.9fr 62px 1.1fr; grid-template-rows:222px 40px; gap:10px 14px; }.reward { display:grid; grid-template-rows:60px 1fr 40px; border:1px solid var(--color-line); border-top:3px solid var(--tone); border-radius:var(--radius-lg); background:var(--tone-bg); overflow:hidden; }.reward--human { --tone:#8492a6; --tone-bg:var(--color-surface); }.reward--verify { --tone:var(--color-rl); --tone-bg:rgba(173,124,255,.035); }.reward header { padding:13px 17px; border-bottom:1px solid var(--color-line-soft); }.reward header span { color:var(--color-muted); font:700 9px/1 ui-monospace; letter-spacing:.09em; }.reward header strong { display:block; color:var(--tone); font-size:18px; margin-top:7px; }.reward footer { display:grid; place-items:center; border-top:1px solid var(--color-line-soft); color:var(--color-muted); font-size:11px; }.human { display:flex; align-items:center; justify-content:center; gap:22px; }.human i { position:relative; width:43px; height:43px; border:1px solid #8492a6; border-radius:50%; }.human i::after { content:""; position:absolute; left:8px; right:8px; bottom:-14px; height:19px; border:1px solid #8492a6; border-radius:20px 20px 0 0; }.human b { color:var(--color-text); font-size:17px; }.versus { display:grid; place-items:center; color:var(--color-muted); font:700 13px/1 ui-monospace; }.checks { display:grid; gap:8px; padding:13px 18px; }.checks div { display:grid; grid-template-columns:52px 1fr 24px; gap:10px; align-items:center; padding:8px 11px; border:1px solid rgba(173,124,255,.3); border-radius:var(--radius-sm); background:var(--color-bg-raised); }.checks b { color:var(--color-rl); font-size:13px; }.checks span { color:var(--color-text-soft); font-size:12px; }.checks i { display:grid; place-items:center; width:20px; height:20px; border-radius:50%; background:var(--color-rl); color:var(--color-bg); font-size:11px; font-style:normal; }.scale-note { grid-column:1 / 4; display:grid; grid-template-columns:auto 1fr auto; gap:14px; align-items:center; padding:0 17px; color:var(--color-muted); font-size:11px; }.scale-note i { height:1px; background:linear-gradient(90deg,var(--color-line),var(--color-rl)); }.scale-note strong { color:var(--color-rl); font-size:14px; }
</style>
