<template>
  <div class="scaling-axes" aria-label="Training-time scaling과 Test-time scaling의 비교">
    <section class="scaling scaling--train"><header><span>AXIS 1</span><strong>Training-time Scaling</strong></header><div class="stack"><i>Model</i><i>Data</i><i>Training compute</i></div><footer>학습 과정에 compute 투입</footer></section>
    <div class="plus">+</div>
    <section class="scaling scaling--test"><header><span>AXIS 2</span><strong>Test-time Scaling</strong></header><div class="budgets"><div><small>Easy</small><b></b><em>small budget</em></div><div><small>Hard</small><b></b><em>larger budget</em></div></div><footer>문제마다 추론 compute 배분</footer></section>
    <div class="allocation"><span>정답을 즉시 생성</span><i></i><strong>생각 · 탐색 · 검증에 계산을 쓴다</strong></div>
  </div>
</template>

<style scoped>
.scaling-axes { height:274px; display:grid; grid-template-columns:1fr 56px 1fr; grid-template-rows:220px 42px; gap:10px 14px; }.scaling { display:grid; grid-template-rows:62px 1fr 42px; border:1px solid var(--color-line); border-top:3px solid var(--tone); border-radius:var(--radius-lg); background:var(--tone-bg); overflow:hidden; }.scaling--train { --tone:#8492a6; --tone-bg:var(--color-surface); }.scaling--test { --tone:var(--color-agency); --tone-bg:rgba(255,180,84,.035); }.scaling header { padding:13px 18px; border-bottom:1px solid var(--color-line-soft); }.scaling header span { color:var(--color-muted); font:700 9px/1 ui-monospace; letter-spacing:.1em; }.scaling header strong { display:block; color:var(--tone); font-size:19px; margin-top:8px; }.scaling footer { display:grid; place-items:center; border-top:1px solid var(--color-line-soft); color:var(--color-muted); font-size:12px; }.stack { display:flex; align-items:flex-end; justify-content:center; gap:12px; padding:22px; }.stack i { display:grid; place-items:center; width:94px; border:1px solid var(--color-line); background:var(--color-bg-raised); color:var(--color-text-soft); font-size:11px; font-style:normal; }.stack i:nth-child(1) { height:42px; }.stack i:nth-child(2) { height:62px; }.stack i:nth-child(3) { height:84px; }.plus { display:grid; place-items:center; color:var(--color-agency); font-size:34px; }.budgets { display:grid; gap:14px; padding:22px 25px; align-content:center; }.budgets div { display:grid; grid-template-columns:44px 1fr 86px; gap:10px; align-items:center; }.budgets small { color:var(--color-text-soft); font-size:12px; }.budgets b { height:8px; border-radius:4px; background:var(--color-line); }.budgets div:last-child b { background:linear-gradient(90deg,rgba(255,180,84,.3),var(--color-agency)); }.budgets em { color:var(--color-muted); font-size:10px; font-style:normal; }.allocation { grid-column:1 / 4; display:grid; grid-template-columns:auto 1fr auto; gap:14px; align-items:center; padding:0 18px; color:var(--color-muted); font-size:12px; }.allocation i { height:1px; background:linear-gradient(90deg,var(--color-line),var(--color-agency)); }.allocation strong { color:var(--color-agency); font-size:14px; }
</style>
